version: "3.9"
services:
    db:
        container_name: database
        image: mariadb:10.5.9
        command: --max_allowed_packet=256M
        volumes:
            - "./db:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        restart: always
        networks:
            - default
    altrp.server:
        depends_on:
            - db
        container_name: altrp
        image: altrp/altrp-js:latest
        expose:
            - "${PORT}"
        ports:
            - "${PORT}:${PORT}"
        restart: always
        networks:
            - default
        stdin_open: true
        tty: true
